### ISSUE TITLE
dof not working when stitching

### ISSUE THREAD

**Issue by laurenchen0631** [studentBC/panoramaProject#15]
dof algorithm will show an error on `video1` on my macbook m1 Ventura.

```
# ...
** On entry to DLASCL, parameter number  4 had an illegal value
** On entry to DLASCL, parameter number  4 had an illegal value
** On entry to DLASCL, parameter number  5 had an illegal value
** On entry to DLASCL, parameter number  4 had an illegal value
** On entry to DLASCL, parameter number  4 had an illegal value
** On entry to DLASCL, parameter number  5 had an illegal value
** On entry to DLASCL, parameter number  4 had an illegal value
** On entry to DLASCL, parameter number  4 had an illegal value
** On entry to DLASCL, parameter number  5 had an illegal value
** On entry to DLASCL, parameter number  4 had an illegal value
** On entry to DLASCL, parameter number  4 had an illegal value
** On entry to DLASCL, parameter number  5 had an illegal value
go stitching ...
stitch Failed! error:  3
Traceback (most recent call last):
  File "/Users/lorne/programs/panoramaProject/main.py", line 132, in <module>
    main(args)
  File "/Users/lorne/programs/panoramaProject/main.py", line 106, in main
    cv2.imwrite("simplePanorama.jpg", sp.simpleStitch())
  File "/Users/lorne/programs/panoramaProject/StitchPanorama.py", line 41, in simpleStitch
    return prev
NameError: name 'prev' is not defined
```

My python version is `3.11.0`, and downgrading `3.9.5` doesn't work as well.

For some input, the dof stitching will create the vertically inverted image.
![simplePanorama](https://user-images.githubusercontent.com/4170738/203486939-f10b8319-22ac-4cb9-a012-740ccd4f2989.jpg)

**Comment by studentBC** [comment]
Have you ever tried calling fillBackground instead of fill_background, maybe this issue will not happen on that case
The root cause might be python stitch library cannot find the common place to stitch after we do background extraction ...

**Comment by studentBC** [comment]
a quick work around should be unmark line 104 and replace it like
sampleBG = [ frames[i] for i in range(0, frame_count, 10) ]
that should solve your problem and let you focus on developing new features first

**Comment by laurenchen0631** [comment]
I would just use some workable algorithm when I develop it for now.
Btw, I updated the issue description.

**Comment by studentBC** [comment]
<img width="889" alt="Screenshot 2022-11-22 at 10 55 41 PM" src="https://user-images.githubusercontent.com/16419868/203487831-d1552227-57e3-4b23-a05a-77d7dbda89d6.png">
For your workaround, change line 101 and 104 it shall works well

**Comment by studentBC** [comment]
As for output upside down problem, we will work on it
